spring.datasource.url: jdbc:mysql://localhost/spl?verifyServerCertificate=false&useSSL=false&requireSSL=false
spring:
  datasource:
    username: spl
    password: splpassword
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: validate

      